import { ImageList, ImageListModel,ListDataSource, AVPlayerClass } from 'shenling_common'
// export * from './advert'
export * from './user'
export * from './tab'
export * from './task'
export * from './router'
export * from './task_detail'
// export * from './common'
export * from './pick_up'
export * from './deliver'
export * from './car_record'
export * from './delay'
export * from './exception'
export * from './location'
export * from './message'
export * from './car'
export  {ImageList,  ImageListModel,  ListDataSource, AVPlayerClass }
// export * from './basic_datasource'
// // 统一的类型工具 用来处理所有的接口的返回类型
// export class ResponsesData<T> {
//   code: number = 0
//   msg: string = ""
//   data: T | null = null
// }